### ISSUE TITLE
aar library

### ISSUE THREAD

**Issue by jtrollia** [winsontan520/Android-WScratchView#15]
Hi,

Thanks for your work, it's really nice.

I uploaded an .aar version of your library here https://github.com/Malivuk/aar-library
It's the first time for me to do so, so maybe it's not optimized.

Anyway, it's the best way to use it with Android Studio.
How to do it:

1) Create a lib folder at the root of your project `MyProject/app/libs`
2) In your build.gradle, add these lines:
`repositories {
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
}`
3) And add the file as depedency:
    `compile(name: 'wscratchview-library', ext: 'aar')`

**Comment by winsontan520** [comment]
Thanks. I am thinking to update library to support gradle

**Comment by apherio** [comment]
yeah that's really great .I will give it a try in few days and update over here
