### ISSUE TITLE
ScratchDrawable

### ISSUE THREAD

**Issue by Grozny** [winsontan520/Android-WScratchView#17]
Hi.
Great job.
This works great for rectangular images and fixed layout_width and layout_height.
But images with contours and shadows does not work.
The bitmap (canvas) lose a lot of quality.

**Comment by winsontan520** [comment]
This is just a quick hack but not proper way, so there will be a lot of other drawbacks. In fact the library should be rewrote with proper way to draw, storing path, minimize loop to draw, reduce overhead, increase performance, memory issue etc. Sorry I don't have much time on time.
