### ISSUE TITLE
Error with R.styleable

### ISSUE THREAD

**Issue by yassine-lafryhi** [winsontan520/Android-WScratchView#26]
![er](https://cloud.githubusercontent.com/assets/17414490/17467710/16f6056c-5d19-11e6-8865-5cf18504de93.png)

**Comment by yassine-lafryhi** [comment]
I found a solution to this issue, it was that I have to Convert switch to if-else:
![yes](https://cloud.githubusercontent.com/assets/17414490/17467961/1a41ca38-5d1b-11e6-9993-d3be52a8ccbe.png)


Source:http://stackoverflow.com/questions/9092712/switch-case-statement-error-case-expressions-must-be-constant-expression

**Comment by joashLlaneza7** [comment]
were you able to use this library in android studio?

**Comment by yassine-lafryhi** [comment]
@joashLlaneza7: Yes I have been able to use it.

**Comment by yassine-lafryhi** [comment]
@joashLlaneza7 : If you want to import this library using android studio you can download this aar file:
https://github.com/Malivuk/aar-library , which created by: @Malivuk and follow these instructions:
http://stackoverflow.com/questions/16682847/how-to-manually-include-external-aar-package-using-new-gradle-android-build-syst#answer-34919810.

**Comment by joashLlaneza7** [comment]
Thank you!!!

**Comment by yassine-lafryhi** [comment]
@joashLlaneza7  You are welcome.

**Comment by joashLlaneza7** [comment]
Hello Yassine! i managed to import the library to android studio but can i ask another question cause im pretty new to android and Im trying to learn with this project. so i tried to test it out with the sample xml code in the read me file but i think i had the same errors as you did but not just in the switch statement but all the R.styleable even the ones outside of the switch. and i also think i have a build error. have you encountered any issues like this?
thank you again!
![screen shot 2016-08-10 at 11 14 22 pm](https://cloud.githubusercontent.com/assets/11295940/17559281/439c4340-5f50-11e6-904c-d4ad6c26ca80.png)

**Comment by yassine-lafryhi** [comment]
Hi @joashLlaneza7! , Please try to download the library (**not aar file**), then import it to android studio by selecting "**Import project (Eclipse ADT,Gradle, etc,)**", after that fix the error in **switch statement**, and it will work!

**Comment by joashLlaneza7** [comment]
Hi @yassine-lafryhi sorry i couldn't reply because of the heavy rains it kinda disabled out internet. Ive tried importing the test project as eclipse adt but it says "gradle sync failed: Cause: failed to find target with hash string 'Google Inc. :Google APIs:19'" i tried changing the compileSdkVersion to 24 and it still doesn't work it still says the same error. Thank you for all the help tho i really appreciated it

**Comment by yassine-lafryhi** [comment]
Hi @joashLlaneza7 there is no problem. Just open the SDK manager and install the following and re-import the project and it will work:
![19](https://cloud.githubusercontent.com/assets/17414490/17647918/77a57838-61fc-11e6-8a7a-97fa01c1e2b3.png)

**Comment by joashLlaneza7** [comment]
Hi @yassine-lafryhi!!! i imported it successfully finally! and no more errors on the code i changed the switch statement to if statement. its working perfectly!!! THANK YOU!

**Comment by yassine-lafryhi** [comment]
No problem @joashLlaneza7  we are here to **help** each other.
